version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
    restart: always

volumes:
  letsencrypt:
    external: true
