version: "3.9"

services:
  nginx:
    build:
      context: ../nginx
      dockerfile: ./Dockerfile
      target: production
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot:/var/www/certbot:ro
      - letsencrypt:/etc/letsencrypt:ro
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - certbot:/var/www/certbot:rw
      - letsencrypt:/etc/letsencrypt:rw
    entrypoint: ["/bin/sh", "-c", "trap exit TERM"]
    restart: on-failure

volumes:
  certbot:
    external: true
  letsencrypt:
    external: true
